### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [Roundaround/mc-fabric-named-traders#1]
Hello, you made it possible!! Great 😊
But I'm curious and you should maybe make it clear (Modrinth description) - keeping one trader means no other one is spawning, one per world?
Or is unlimited spawning possible?

Thanks already, greetings.

**Comment by Roundaround** [comment]
Hi! I'm looking through the vanilla Minecraft code and don't see anything that would prevent additional traders from spawning, so you should be able to get unlimited traders!

From what I can tell in vanilla Minecraft, a wandering trader attempts to spawn once every 20 minutes and the chance that it succeeds in spawning is pretty low (2.5% on the first try), making one spawn only on average every 4.5-5 hours. Since in vanilla they despawn after 40 minutes, it is very unlikely that you'll ever see two at once.

**Comment by ghost** [comment]
Interesting, thanks!
